### ISSUE TITLE
ICLabel error

### ISSUE THREAD

**Issue by ldestefa** [cincibrainlab/vhtp#22]
We receive the error "Failed to Run ICLabel. Trying to compile MEX-files." then it continues to take an 80x slower route

**Comment by KCull887** [comment]
Installed necessary matconvnet dependencies of libjpeg via build-essentials and libjpeg-turbo8-dev along with setting up mex for C++ compilation via g++.  Allowed for proper mex compilation for vl_compilenn method called in ICLabel plugin.
