### ISSUE TITLE
Update component removal to fix visualization

### ISSUE THREAD

**Issue by ldestefa** [cincibrainlab/vhtp#29]
Running into issues removing components due to reliance on unavailable Statistics and Machine Learning toolbox for visualization

**Comment by KCull887** [comment]
Added ability to switch between eeglab native visualization (no dependencies) and vis_artifacts from clean_rawdata plugin (relies upon Statistics and Machine Learning Toolbox).  See commit 51db27cd7fde6f7be7c5a5cc93919e6b4430c88a for details.
