### ISSUE TITLE
Only create subfolders when necessary

### ISSUE THREAD

**Issue by ldestefa** [cincibrainlab/vhtp#35]
Right now, subfolders to house saved files are created when the function is run even if there is no output to save, so many empty folders are created. It would be easier to find output data if folders were only created when data was saved.

**Comment by KCull887** [comment]
Made subdirectories indicating function used for each step to only be created when output is explicitly marked to be saved.  See commit 8170bfe9b22f350ae14a6384688dec2f38602552
