### ISSUE TITLE
Can't auto-plot >35 components

### ISSUE THREAD

**Issue by ldestefa** [cincibrainlab/vhtp#39]
Pipeline throws an error if you set >35 components to plot; have to plot extra manually.

**Comment by KCull887** [comment]
Fixed plotting to allow values greater than 35 for the 'maxcomps' parameter, see commit 2eed422ccd8f912e4e833672c15012ef14f324a4.

Added optional parameter to allow user to define frequency range of interest for extended detail plotting for each component, see commit aadcd05fd3a11ef405d1b9b09d104ae18589d6b0.
